### ISSUE TITLE
Create Merch Page

### ISSUE THREAD

**Issue by mavyfaby** [csps/web#7]
## Tasks

- [ ] List of all products
- [ ] Product details
- [ ] Name
- [ ] Description
- [ ] Price
- [ ] Quantity
- [ ] Variation
- [ ] Mode of Payment
- [ ] QR Code Link of the product
- [ ] Buy now
- [ ] Add to cart
- [ ] Success and Error dialog
